clients:
  - alias: "RTI"
    RTI_host: True
    user: loolirer
    hostname: bootplug
    mac_address: "CC:47:40:FA:A0:E1"
    resolution: [960, 720]
    intrinsic_matrix:
      - [720.313, 000.000, 481.014]
      - [000.000, 719.521, 360.991]
      - [000.000, 000.000, 001.000]
    distortion_model: "fisheye"
    distortion_coefficients: [0.395621, 0.63370, -2.41723, 2.11079]

  - alias: "Camera 3"
    RTI_host: False
    user: linguafranca
    hostname: raspmcs03
    mac_address: "2C:CF:67:9C:14:57"
    resolution: [960, 720]
    intrinsic_matrix:
      - [768.113, 000.000, 472.596]
      - [000.000, 767.935, 350.978]
      - [000.000, 000.000, 001.000]
    distortion_model: "fisheye"
    distortion_coefficients: [0.368917, 1.50111, -7.94126, 11.9171]

#  - alias: "Camera 1"
#    RTI_host: False
#    user: linguafranca
#    hostname: raspmcs01
#    mac_address: "2C:CF:67:9C:14:56"
#    resolution: [960, 720]
#    intrinsic_matrix:
#      - [768.113, 000.000, 472.596]
#      - [000.000, 767.935, 350.978]
#      - [000.000, 000.000, 001.000]
#    distortion_model: "fisheye"
#    distortion_coefficients: [0.368917, 1.50111, -7.94126, 11.9171]
#
#  - alias: "Camera 2"
#    RTI_host: False
#    user: omni
#    hostname: raspmcs02
#    mac_address: "2C:CF:67:9C:14:56"
#    resolution: [960, 720]
#    intrinsic_matrix:
#      - [768.113, 000.000, 472.596]
#      - [000.000, 767.935, 350.978]
#      - [000.000, 000.000, 001.000]
#    distortion_model: "fisheye"
#    distortion_coefficients: [0.368917, 1.50111, -7.94126, 11.9171]
#
#  - alias: "Camera 4"
#    RTI_host: False
#    user: linguafranca
#    hostname: raspmcs04
#    mac_address: "2C:CF:67:9C:14:56"
#    resolution: [960, 720]
#    intrinsic_matrix:
#      - [768.113, 000.000, 472.596]
#      - [000.000, 767.935, 350.978]
#      - [000.000, 000.000, 001.000]
#    distortion_model: "fisheye"
#    distortion_coefficients: [0.368917, 1.50111, -7.94126, 11.9171]